sortedService:
  file: "src/main/resources/unsorted_1.txt"
  sorted-file: "src/main/resources/sorted.txt"
  lines-count-in-one-file: "100"

fileGenerationService:
  file: "src/main/resources/unsorted_1.txt"
  max-length-lines: "1000"
  lines-count: "1000"
